export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string;
          first_name: string;
          last_name: string;
          avatar_url: string | null;
          phone: string | null;
          preferences: Json;
          status: 'active' | 'inactive' | 'suspended';
          role: 'user' | 'admin' | 'super_admin';
          onboarding_completed: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name: string;
          first_name: string;
          last_name: string;
          avatar_url?: string | null;
          phone?: string | null;
          preferences?: Json;
          status?: 'active' | 'inactive' | 'suspended';
          role?: 'user' | 'admin' | 'super_admin';
          onboarding_completed?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string;
          first_name?: string;
          last_name?: string;
          avatar_url?: string | null;
          phone?: string | null;
          preferences?: Json;
          status?: 'active' | 'inactive' | 'suspended';
          role?: 'user' | 'admin' | 'super_admin';
          onboarding_completed?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          type: 'personal' | 'team' | 'corporate';
          owner_id: string;
          owner_email: string;
          settings: Json;
          approval_workflow: Json;
          plan: 'free' | 'collect' | 'control';
          status: 'active' | 'archived';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          type?: 'personal' | 'team' | 'corporate';
          owner_id: string;
          owner_email: string;
          settings?: Json;
          approval_workflow?: Json;
          plan?: 'free' | 'collect' | 'control';
          status?: 'active' | 'archived';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          type?: 'personal' | 'team' | 'corporate';
          owner_id?: string;
          owner_email?: string;
          settings?: Json;
          approval_workflow?: Json;
          plan?: 'free' | 'collect' | 'control';
          status?: 'active' | 'archived';
          created_at?: string;
          updated_at?: string;
        };
      };
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string | null;
          email: string;
          display_name: string;
          avatar_url: string | null;
          role: 'owner' | 'admin' | 'approver' | 'member' | 'auditor';
          approver_id: string | null;
          department_id: string | null;
          employee_id: string | null;
          spending_limit: number | null;
          status: 'active' | 'invited' | 'removed';
          invited_at: string;
          joined_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id?: string | null;
          email: string;
          display_name: string;
          avatar_url?: string | null;
          role?: 'owner' | 'admin' | 'approver' | 'member' | 'auditor';
          approver_id?: string | null;
          department_id?: string | null;
          employee_id?: string | null;
          spending_limit?: number | null;
          status?: 'active' | 'invited' | 'removed';
          invited_at?: string;
          joined_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string | null;
          email?: string;
          display_name?: string;
          avatar_url?: string | null;
          role?: 'owner' | 'admin' | 'approver' | 'member' | 'auditor';
          approver_id?: string | null;
          department_id?: string | null;
          employee_id?: string | null;
          spending_limit?: number | null;
          status?: 'active' | 'invited' | 'removed';
          invited_at?: string;
          joined_at?: string | null;
        };
      };
      expenses: {
        Row: {
          id: string;
          user_id: string;
          user_email: string;
          user_display_name: string;
          workspace_id: string;
          merchant: string;
          description: string | null;
          amount: number;
          currency: string;
          converted_amount: number | null;
          converted_currency: string | null;
          category_id: string | null;
          category_name: string | null;
          tag_ids: string[];
          tag_names: string[];
          date: string;
          receipt_id: string | null;
          receipt_url: string | null;
          receipt_thumbnail_url: string | null;
          has_receipt: boolean;
          source: 'manual' | 'scan' | 'card' | 'email' | 'import';
          card_last4: string | null;
          type: 'standard' | 'mileage' | 'per_diem' | 'time';
          mileage: Json | null;
          report_id: string | null;
          report_name: string | null;
          status: 'unreported' | 'reported' | 'submitted' | 'approved' | 'rejected' | 'reimbursed';
          attendees: Json;
          splits: Json | null;
          violations: Json;
          ai_confidence: number | null;
          ai_suggestions: Json | null;
          comment_count: number;
          last_comment_at: string | null;
          is_duplicate: boolean;
          is_billable: boolean;
          is_reimbursable: boolean;
          is_recurring: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_email: string;
          user_display_name: string;
          workspace_id: string;
          merchant: string;
          description?: string | null;
          amount: number;
          currency?: string;
          converted_amount?: number | null;
          converted_currency?: string | null;
          category_id?: string | null;
          category_name?: string | null;
          tag_ids?: string[];
          tag_names?: string[];
          date: string;
          receipt_id?: string | null;
          receipt_url?: string | null;
          receipt_thumbnail_url?: string | null;
          has_receipt?: boolean;
          source?: 'manual' | 'scan' | 'card' | 'email' | 'import';
          card_last4?: string | null;
          type?: 'standard' | 'mileage' | 'per_diem' | 'time';
          mileage?: Json | null;
          report_id?: string | null;
          report_name?: string | null;
          status?: 'unreported' | 'reported' | 'submitted' | 'approved' | 'rejected' | 'reimbursed';
          attendees?: Json;
          splits?: Json | null;
          violations?: Json;
          ai_confidence?: number | null;
          ai_suggestions?: Json | null;
          comment_count?: number;
          last_comment_at?: string | null;
          is_duplicate?: boolean;
          is_billable?: boolean;
          is_reimbursable?: boolean;
          is_recurring?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_email?: string;
          user_display_name?: string;
          workspace_id?: string;
          merchant?: string;
          description?: string | null;
          amount?: number;
          currency?: string;
          converted_amount?: number | null;
          converted_currency?: string | null;
          category_id?: string | null;
          category_name?: string | null;
          tag_ids?: string[];
          tag_names?: string[];
          date?: string;
          receipt_id?: string | null;
          receipt_url?: string | null;
          receipt_thumbnail_url?: string | null;
          has_receipt?: boolean;
          source?: 'manual' | 'scan' | 'card' | 'email' | 'import';
          card_last4?: string | null;
          type?: 'standard' | 'mileage' | 'per_diem' | 'time';
          mileage?: Json | null;
          report_id?: string | null;
          report_name?: string | null;
          status?: 'unreported' | 'reported' | 'submitted' | 'approved' | 'rejected' | 'reimbursed';
          attendees?: Json;
          splits?: Json | null;
          violations?: Json;
          ai_confidence?: number | null;
          ai_suggestions?: Json | null;
          comment_count?: number;
          last_comment_at?: string | null;
          is_duplicate?: boolean;
          is_billable?: boolean;
          is_reimbursable?: boolean;
          is_recurring?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      expense_reports: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          user_id: string;
          user_email: string;
          user_display_name: string;
          workspace_id: string;
          expense_ids: string[];
          expense_count: number;
          total_amount: number;
          currency: string;
          category_breakdown: Json;
          status: 'draft' | 'submitted' | 'approved' | 'rejected' | 'processing' | 'reimbursed' | 'closed';
          approvals: Json;
          current_approval_level: number;
          submitted_at: string | null;
          approved_at: string | null;
          rejected_at: string | null;
          reimbursed_at: string | null;
          reimbursement: Json | null;
          violation_count: number;
          has_blocking_violations: boolean;
          chat_id: string | null;
          comment_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          user_id: string;
          user_email: string;
          user_display_name: string;
          workspace_id: string;
          expense_ids?: string[];
          expense_count?: number;
          total_amount?: number;
          currency?: string;
          category_breakdown?: Json;
          status?: 'draft' | 'submitted' | 'approved' | 'rejected' | 'processing' | 'reimbursed' | 'closed';
          approvals?: Json;
          current_approval_level?: number;
          submitted_at?: string | null;
          approved_at?: string | null;
          rejected_at?: string | null;
          reimbursed_at?: string | null;
          reimbursement?: Json | null;
          violation_count?: number;
          has_blocking_violations?: boolean;
          chat_id?: string | null;
          comment_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          user_id?: string;
          user_email?: string;
          user_display_name?: string;
          workspace_id?: string;
          expense_ids?: string[];
          expense_count?: number;
          total_amount?: number;
          currency?: string;
          category_breakdown?: Json;
          status?: 'draft' | 'submitted' | 'approved' | 'rejected' | 'processing' | 'reimbursed' | 'closed';
          approvals?: Json;
          current_approval_level?: number;
          submitted_at?: string | null;
          approved_at?: string | null;
          rejected_at?: string | null;
          reimbursed_at?: string | null;
          reimbursement?: Json | null;
          violation_count?: number;
          has_blocking_violations?: boolean;
          chat_id?: string | null;
          comment_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          workspace_id: string | null;
          name: string;
          code: string;
          icon: string;
          color: string;
          parent_id: string | null;
          enabled: boolean;
          require_comment: boolean;
          max_amount: number | null;
          tax_rate: number | null;
          sort_order: number;
          is_system: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id?: string | null;
          name: string;
          code: string;
          icon?: string;
          color?: string;
          parent_id?: string | null;
          enabled?: boolean;
          require_comment?: boolean;
          max_amount?: number | null;
          tax_rate?: number | null;
          sort_order?: number;
          is_system?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string | null;
          name?: string;
          code?: string;
          icon?: string;
          color?: string;
          parent_id?: string | null;
          enabled?: boolean;
          require_comment?: boolean;
          max_amount?: number | null;
          tax_rate?: number | null;
          sort_order?: number;
          is_system?: boolean;
          created_at?: string;
        };
      };
      receipts: {
        Row: {
          id: string;
          expense_id: string | null;
          user_id: string;
          original_url: string;
          thumbnail_url: string | null;
          file_name: string;
          file_type: string;
          file_size: number;
          ocr_status: 'pending' | 'processing' | 'completed' | 'failed';
          ocr_raw_text: string | null;
          ocr_extracted_data: Json | null;
          confidence: number | null;
          needs_human_review: boolean;
          processed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          expense_id?: string | null;
          user_id: string;
          original_url: string;
          thumbnail_url?: string | null;
          file_name: string;
          file_type: string;
          file_size: number;
          ocr_status?: 'pending' | 'processing' | 'completed' | 'failed';
          ocr_raw_text?: string | null;
          ocr_extracted_data?: Json | null;
          confidence?: number | null;
          needs_human_review?: boolean;
          processed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          expense_id?: string | null;
          user_id?: string;
          original_url?: string;
          thumbnail_url?: string | null;
          file_name?: string;
          file_type?: string;
          file_size?: number;
          ocr_status?: 'pending' | 'processing' | 'completed' | 'failed';
          ocr_raw_text?: string | null;
          ocr_extracted_data?: Json | null;
          confidence?: number | null;
          needs_human_review?: boolean;
          processed_at?: string | null;
          created_at?: string;
        };
      };
      chats: {
        Row: {
          id: string;
          type: 'direct' | 'group' | 'expense' | 'report' | 'workspace' | 'invoice';
          workspace_id: string | null;
          related_entity_id: string | null;
          related_entity_type: string | null;
          participant_ids: string[];
          participant_details: Json;
          name: string | null;
          icon_url: string | null;
          last_message: Json | null;
          message_count: number;
          unread_counts: Json;
          is_muted: Json;
          is_pinned: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type?: 'direct' | 'group' | 'expense' | 'report' | 'workspace' | 'invoice';
          workspace_id?: string | null;
          related_entity_id?: string | null;
          related_entity_type?: string | null;
          participant_ids?: string[];
          participant_details?: Json;
          name?: string | null;
          icon_url?: string | null;
          last_message?: Json | null;
          message_count?: number;
          unread_counts?: Json;
          is_muted?: Json;
          is_pinned?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: 'direct' | 'group' | 'expense' | 'report' | 'workspace' | 'invoice';
          workspace_id?: string | null;
          related_entity_id?: string | null;
          related_entity_type?: string | null;
          participant_ids?: string[];
          participant_details?: Json;
          name?: string | null;
          icon_url?: string | null;
          last_message?: Json | null;
          message_count?: number;
          unread_counts?: Json;
          is_muted?: Json;
          is_pinned?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          chat_id: string;
          sender_id: string;
          sender_name: string;
          sender_avatar_url: string | null;
          type: 'text' | 'system' | 'expense' | 'report' | 'attachment' | 'task';
          text: string;
          html: string | null;
          attachments: Json | null;
          mentions: Json | null;
          parent_message_id: string | null;
          thread_message_count: number;
          reactions: Json;
          task: Json | null;
          is_edited: boolean;
          is_deleted: boolean;
          edited_at: string | null;
          sent_at: string;
        };
        Insert: {
          id?: string;
          chat_id: string;
          sender_id: string;
          sender_name: string;
          sender_avatar_url?: string | null;
          type?: 'text' | 'system' | 'expense' | 'report' | 'attachment' | 'task';
          text: string;
          html?: string | null;
          attachments?: Json | null;
          mentions?: Json | null;
          parent_message_id?: string | null;
          thread_message_count?: number;
          reactions?: Json;
          task?: Json | null;
          is_edited?: boolean;
          is_deleted?: boolean;
          edited_at?: string | null;
          sent_at?: string;
        };
        Update: {
          id?: string;
          chat_id?: string;
          sender_id?: string;
          sender_name?: string;
          sender_avatar_url?: string | null;
          type?: 'text' | 'system' | 'expense' | 'report' | 'attachment' | 'task';
          text?: string;
          html?: string | null;
          attachments?: Json | null;
          mentions?: Json | null;
          parent_message_id?: string | null;
          thread_message_count?: number;
          reactions?: Json;
          task?: Json | null;
          is_edited?: boolean;
          is_deleted?: boolean;
          edited_at?: string | null;
          sent_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          issuer_id: string;
          issuer_workspace_id: string;
          issuer_name: string;
          issuer_email: string;
          issuer_address: string | null;
          issuer_logo: string | null;
          recipient_name: string;
          recipient_email: string;
          recipient_address: string | null;
          recipient_phone: string | null;
          invoice_number: string;
          purchase_order_number: string | null;
          issue_date: string;
          due_date: string;
          currency: string;
          line_items: Json;
          subtotal: number;
          tax_total: number;
          discount_amount: number;
          discount_type: string | null;
          total_amount: number;
          status: 'draft' | 'sent' | 'viewed' | 'paid' | 'overdue' | 'cancelled';
          paid_at: string | null;
          paid_amount: number;
          payment_method: string | null;
          chat_id: string | null;
          notes: string;
          terms: string;
          sent_at: string | null;
          viewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          issuer_id: string;
          issuer_workspace_id: string;
          issuer_name: string;
          issuer_email: string;
          issuer_address?: string | null;
          issuer_logo?: string | null;
          recipient_name: string;
          recipient_email: string;
          recipient_address?: string | null;
          recipient_phone?: string | null;
          invoice_number: string;
          purchase_order_number?: string | null;
          issue_date: string;
          due_date: string;
          currency?: string;
          line_items?: Json;
          subtotal?: number;
          tax_total?: number;
          discount_amount?: number;
          discount_type?: string | null;
          total_amount?: number;
          status?: 'draft' | 'sent' | 'viewed' | 'paid' | 'overdue' | 'cancelled';
          paid_at?: string | null;
          paid_amount?: number;
          payment_method?: string | null;
          chat_id?: string | null;
          notes?: string;
          terms?: string;
          sent_at?: string | null;
          viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          issuer_id?: string;
          issuer_workspace_id?: string;
          issuer_name?: string;
          issuer_email?: string;
          issuer_address?: string | null;
          issuer_logo?: string | null;
          recipient_name?: string;
          recipient_email?: string;
          recipient_address?: string | null;
          recipient_phone?: string | null;
          invoice_number?: string;
          purchase_order_number?: string | null;
          issue_date?: string;
          due_date?: string;
          currency?: string;
          line_items?: Json;
          subtotal?: number;
          tax_total?: number;
          discount_amount?: number;
          discount_type?: string | null;
          total_amount?: number;
          status?: 'draft' | 'sent' | 'viewed' | 'paid' | 'overdue' | 'cancelled';
          paid_at?: string | null;
          paid_amount?: number;
          payment_method?: string | null;
          chat_id?: string | null;
          notes?: string;
          terms?: string;
          sent_at?: string | null;
          viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      bills: {
        Row: {
          id: string;
          workspace_id: string;
          uploaded_by_id: string;
          vendor_name: string;
          vendor_email: string | null;
          vendor_address: string | null;
          bill_number: string | null;
          issue_date: string;
          due_date: string;
          currency: string;
          total_amount: number;
          line_items: Json;
          status: 'pending' | 'approved' | 'scheduled' | 'paid' | 'overdue' | 'cancelled';
          approver_id: string | null;
          approved_at: string | null;
          payment_method: string | null;
          payment_date: string | null;
          payment_reference: string | null;
          attachment_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          uploaded_by_id: string;
          vendor_name: string;
          vendor_email?: string | null;
          vendor_address?: string | null;
          bill_number?: string | null;
          issue_date: string;
          due_date: string;
          currency?: string;
          total_amount: number;
          line_items?: Json;
          status?: 'pending' | 'approved' | 'scheduled' | 'paid' | 'overdue' | 'cancelled';
          approver_id?: string | null;
          approved_at?: string | null;
          payment_method?: string | null;
          payment_date?: string | null;
          payment_reference?: string | null;
          attachment_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          uploaded_by_id?: string;
          vendor_name?: string;
          vendor_email?: string | null;
          vendor_address?: string | null;
          bill_number?: string | null;
          issue_date?: string;
          due_date?: string;
          currency?: string;
          total_amount?: number;
          line_items?: Json;
          status?: 'pending' | 'approved' | 'scheduled' | 'paid' | 'overdue' | 'cancelled';
          approver_id?: string | null;
          approved_at?: string | null;
          payment_method?: string | null;
          payment_date?: string | null;
          payment_reference?: string | null;
          attachment_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: 'expense_approved' | 'expense_rejected' | 'report_submitted' | 'report_approved' | 'report_rejected' | 'chat_message' | 'invoice_paid' | 'bill_due' | 'policy_violation' | 'task_assigned' | 'mention' | 'system';
          title: string;
          body: string;
          data: Json;
          actor_id: string | null;
          actor_name: string | null;
          actor_avatar_url: string | null;
          is_read: boolean;
          read_at: string | null;
          action_url: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'expense_approved' | 'expense_rejected' | 'report_submitted' | 'report_approved' | 'report_rejected' | 'chat_message' | 'invoice_paid' | 'bill_due' | 'policy_violation' | 'task_assigned' | 'mention' | 'system';
          title: string;
          body: string;
          data?: Json;
          actor_id?: string | null;
          actor_name?: string | null;
          actor_avatar_url?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          action_url: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'expense_approved' | 'expense_rejected' | 'report_submitted' | 'report_approved' | 'report_rejected' | 'chat_message' | 'invoice_paid' | 'bill_due' | 'policy_violation' | 'task_assigned' | 'mention' | 'system';
          title?: string;
          body?: string;
          data?: Json;
          actor_id?: string | null;
          actor_name?: string | null;
          actor_avatar_url?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          action_url?: string;
          created_at?: string;
        };
      };
      tags: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          color?: string;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          color?: string;
          created_by?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
